learning_rate: 0.0001
batch_size: 64
buffer_size: 100000
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay: 0.995
target_update_freq: 10
max_episodes: 1000
max_steps_per_episode: 1000
bc_dataset_path: data/bc_data.npz
model_save_path: models/dqn_model.pth
hybrid_lr: 0.00001