name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev
    
    - name: Build C++ game
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
    
    - name: Test Python components
      run: |
        python -m pytest tests/unit/ -v
    
    - name: Test data creation
      run: |
        python scripts/data_collection/create_sample_data.py --samples 10
    
    - name: Test training
      run: |
        python scripts/training/train_bc.py --data data/bc_data.npz --model models/bc_model.pth --epochs 2